apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/nguyenhainam9122003/develop.env.git
        revision: master
        directories:
          - path: workload/*/overlays/dev
  template:
    metadata:
      name: "{{path[1]}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/nguyenhainam9122003/develop.env.git
        targetRevision: master
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path[1]}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
