apiVersion: v1
kind: ConfigMap
metadata:
  name: pet-be-config
data:
  PORT: "8888"
  MONGO_URL: "mongodb://pet-mongo:27017/pet-be"
  JWT_ACCES_EXPIRE: "1d"
  JWT_REFRESH_EXPIRE: "7d"
  SHOULD_INIT: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: pet-be-secret
type: Opaque
stringData:
  JWT_ACCESS_TOKEN: "demo-access-secret-change-me"
  JWT_REFRESH_TOKEN: "demo-refresh-secret-change-me"
  INIT_PASSWORD: "demo-password-change-me"
