apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-be
  template:
    metadata:
      labels:
        app: pet-be
    spec:
      containers:
        - name: pet-be
          image: ghcr.io/nguyenhainam912/pet-be:latest
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: pet-be-config
            - secretRef:
                name: pet-be-secret
